SECRET_KEY = 'CLoDcG1/PqyXbU/WYUn7XXotj9gukGaC+Z9fwBQ6UfYDgJzP7/fFVhhtRuQTNt7Cq8tYO76NWyUjKCYt'
SECURITY_PASSWORD_SALT = 'PqEUXT86+7WDssAfOrRlAHWVD04BsLADGJeVE7D18+dd+y10SYvZuafD96oSnzQ+oQmOrtsw+wKu0/N8'
SQLALCHEMY_DATABASE_URI = 'sqlite:///uspeda.db'